# ***Learning NumPy***

In [1]:
import numpy as np

### **7 Ways of Creating NumPy Array**

In [3]:
# np.array([Pass a list as parameter])
a = np.array([1,2,3,4,5])

# np.arange(start, end, step)  #step basically tells how to to skip
b = np.arange(1,11,2)

# np.ones(rows, columns) or np.ones(shape) # shape can be (2,2,2,2)
c = np.ones((3,4))

# np.zeros(shape)
d = np.zeros((4,3))

# np.random.random(shape) # it generates random numbers between 0 and 1. It takes the shape as input.
f = np.random.random((2,3))

# np.identity(no. of ones) # it takes only one input as identity matrix is always square.
e = np.identity(3)

# np.linspace(start, end, no. of elements) # it generates linearly spaced numbers between start and end. It takes the number of elements as input.
g = np.linspace(1,10,6)


print(f"np.array([list]): \n {a} \n")
print(f"np.arange(Range): \n {b} \n")
# print(f"np.ones((Pass a tupple with the shape of matrix)): \n {c} \n")
# print(f"np.zeros((Shape)): \n {d} \n")
# print(f"np.identity(no. of ones): \n {e} \n")
# print(f"np.random.random((Shape)): \n {f} \n")
# print(f"np.linspace(1,10,6): \n {g} \n")


np.array([list]): 
 [1 2 3 4 5] 

np.arange(Range): 
 [1 3 5 7 9] 



##### **NOTE**: 
- Some of these take 'list' as parameter others take 'tupple' and some even take 'seperators' as their parameter (eg. linspace takes seperators)

***Bonus***: 8th way to create a NumPy Array

In [4]:
# np.eye(n, m, k) 
# Similar to np.identity it generates a 2-D array with ones on the diagonal and zeros elsewhere. 
# Catch: With np.eye any diagonal of the matrix can be 1's while rest stay zero.
# Catch: while np.identity strictly creates square matrix m*m, with np.eye we can create rectangular matrix or m*n.

# It takes three parameters n, m and k. n is the number of rows, m is the number of columns & k is diagonal number. 
# By default k is 0 which means the main diagonal. If k is positive then it will be upper diagonal and if k is negative then it will be lower diagonal. This is better understood by examples bellow

a = np.eye(3, k = 0) 

b = np.eye(3, k = 1)

c = np.eye(3, k = -2)

# print(f"np.eye(3): \n {a}")
# print(f"np.eye(3, k = 1): \n {b}")
# print(f"np.eye(3, k = -1): \n {c}") 


## Playing with NumPy Array's

In [5]:
# Assigning data type to np.array
a = np.array([1,2,3,4,5], dtype = float)
print(a, end = "\n\n")

# it shows the data type of the array.
print(a.dtype, end = "\n\n")

# it converts the data type of the array to int.
print(a.astype(int).dtype, end = "\n\n")

# there are other ways as well but less popular and less recommended


[1. 2. 3. 4. 5.]

float64

int64



In [6]:
# Learning how arange behave
a = np.arange(13) # default start is 0 and default step is 1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


## **Dimensions of Array**

#### **0-D Array**
- Also known as Scalar

In [7]:
# A zero dimensional array is also called a scalar in numpy 

a = np.array(13)

print(a)

13


#### **1D Array**
- An array that has scalars as its elements is called 1-d array.

In [8]:
b = np.array([1,2,3,4,5])
print(b)

[1 2 3 4 5]


#### **2D Array**
- An array that has 1-D arrays as its elements is called a 2-D array.
- These are often used to represent matrix or 2nd order tensors.



In [9]:
c = np.array([[1,2,3], [4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


#### **3D Array**
- An array that has 2d array as its elements is called a 3d array
- these are often used to represent matrix or 3rd order tensors

In [10]:
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### **Checking the dimension of an array**
-NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [11]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### **Higher Dimensional array**
- Define the number of dimensions by using the ndmin argument

In [12]:
e = np.array([1,2,3,4,5], ndmin=5)

print(e.ndim, "\n")

print(e)
# In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.



5 

[[[[[1 2 3 4 5]]]]]


In [13]:
f = np.array([
    [
        [ [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5] ],
        [ [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5] ],
        [ [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5] ]
    ], 
    [
        [ [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5] ],
        [ [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5] ],
        [ [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5] ]
    ]
])
print(f'f.ndim: {f.ndim} \n')
print(f'f.shape: {f.shape} \n')
print(f'f.size: {f.size} \n')
print(f'f.dtype: {f.dtype} \n')
# print(f'f: \n {f} \n')

f.ndim: 4 

f.shape: (2, 3, 4, 5) 

f.size: 120 

f.dtype: int64 

