### **Array Attributes**

In [1]:
import numpy as np

In [2]:
# Creating 3 different arrays with different dimensions and dtypes
a1 = np.arange(10, dtype=np.int32) 
a2 = np.arange(12,dtype=np.float64).reshape(3,4)
a3 = np.arange(8, dtype=np.float64).reshape(2,2,2)

print(a1, end="\n\n")
print(a2, end="\n\n")
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]


In [7]:
# Dimension
print(f'a1 dimension: {a1.ndim}')
print(f'a2 dimension: {a2.ndim}')
print(f'a3 dimension: {a3.ndim}')

a1 dimension: 1
a2 dimension: 2
a3 dimension: 3


In [5]:
# shape
print(f'a1 shape: {a1.shape}')
print(f'a2 shape: {a2.shape}')
print(f'a3 shape: {a3.shape}')

a1 shape: (10,)
a2 shape: (3, 4)
a3 shape: (2, 2, 2)


In [18]:
# Size
print(f'a1 size: {a1.size}')
print(f'a2 size: {a2.size}')
print(f'a3 size: {a3.size}')

a1 size: 10
a2 size: 12
a3 size: 8


In [19]:
# Itemsize
print(f'a1 itemsize: {a1.itemsize} bytes')
print(f'a2 itemsize: {a2.itemsize} bytes')
print(f'a3 itemsize: {a3.itemsize} bytes')

a1 itemsize: 4 bytes
a2 itemsize: 8 bytes
a3 itemsize: 8 bytes


In [ ]:
# Dtype
print(f'a1 dtype: {a1.dtype}')
print(f'a2 dtype: {a2.dtype}')
print(f'a3 dtype: {a3.dtype}')

a1 dtype: int64
a2 dtype: float64
a3 dtype: int64


In [ ]:
# Changing dtype ---> astype() method
cd = a2.astype('complex128')

print(f'a2 dtype: {a2.dtype}')
print(f'cd dtype: {cd.dtype}')

print(f'cd: \n{cd}')

a2 dtype: float64
cd dtype: complex128
cd: 
[[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j]
 [ 4.+0.j  5.+0.j  6.+0.j  7.+0.j]
 [ 8.+0.j  9.+0.j 10.+0.j 11.+0.j]]
