### **Array Operations**

In [1]:
import numpy as np

Array operations can be broadly be classified into 
- **scalar operations**
- **vector operations**

In [2]:
# Array creation: For further operations
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1, end="\n\n")
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


#### **Scalar Operations**
- In scalar operations, we perform an operation between an array and a scalar value. The operation is applied to each element of the array. Eg. [1,2,3] + 10 = [11,12,13]
- Scalar operations are of Following types:
    - Arithmetic Scalar Operations -> +, -, *, /, **, etc.
    - Comparison Scalar Operations -> >, <, ==, !=, etc.
    - Logical Scalar Operations -> &, |, ~, etc.
    - Assinment Scalar Operations -> +=, -=, *=, /=, etc.
    - Mathematical Scalar Operations -> np.sin(), np.cos(), np.exp(), np.log(), etc.
    - Etc.

In [3]:
# Arithmetic Scalar Operations
print(a1 * 10, end="\n\n")
# print(a2 / 10, end="\n\n")
# print(a1 ** 2, end="\n\n")

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]



In [4]:
# Comparison Scalar Operations
print(a1 > 5, end="\n\n")
# print(a1 == 5, end="\n\n")
# print(a1 != 5, end="\n\n")

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]



In [5]:
# Logical Scalar Operations
# print((a1 > 5) & (a1 < 10), end="\n\n")
print((a1 > 6) | (a1 < 5), end="\n\n")
# print(~(a1 > 0), end="\n\n")

[[ True  True  True  True]
 [ True False False  True]
 [ True  True  True  True]]



In [6]:
# Assignment Scalar Operations

# a1 += 10
# print(a1, end="\n\n")
# a1 -= 10
# print(a1, end="\n\n")

### **Vector Operations**
- In vector operations, we perform an operation between two arrays of same or comparable shape. 
- The operation is applied element-wise between the two arrays. 
- Eg. [1,2,3] + [4,5,6] = [5,7,9]

In [7]:
# Same shape vector operations

print(a1+a2, end="\n\n")
# print(a1-a2, end="\n\n")
# print(a1*a2, end="\n\n")

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]



In [8]:
print(a1 * a2)

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


- **Broadcasting** is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes. It automatically expands the smaller array to match the shape of the larger array, enabling element-wise operations without explicit replication of data. This feature is particularly useful for performing operations between arrays of different sizes and dimensions, making code more concise and efficient.

+ Below is an example of broadcasting or similar shape vector operations.

In [9]:
# Similar shape vector operations

a3 = np.array([10, 10, 10, 10])
print(a1+a3, end="\n\n")

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]



### **Aggregation Operations**

In [10]:
# Creating a random array for further use
# a1 = np.random.random((3,3))
# a1 = np.round(a1*100)
a1 = np.round(np.random.random((3,3))*100) # same thing as above but in one line
a1

array([[48.,  6., 76.],
       [31., 91., 49.],
       [93.,  5., 54.]])

In [11]:
# Aggregation Operations: Entire Array
# max/min/sum/prod are some of the aggregation operations that can be performed on arrays.

print(np.sum(a1), end="\n\n") # sums up all the elements in the array and returns a single value
print(np.prod(a1), end="\n\n") # multiplies all the elements in the array and returns a single value
print(np.max(a1), end="\n\n") # returns

453.0

75971719998720.0

93.0



In [12]:
# Aggregation Operations: Along an Axis
print(f'Sum of each col: \n{np.sum(a1, axis=0)}', end="\n\n") # sums up each column and returns a vector of the sums of each column
print(f'Sum of each row: \n{np.sum(a1, axis=1)}', end="\n\n") # sums up each row

Sum of each col: 
[172. 102. 179.]

Sum of each row: 
[130. 171. 152.]



In [13]:
print(a1, end='\n\n')
print(np.max(a1)) # returns the maximum value in the array
print(np.max(a1, axis=0)) # returns the maximum value in each column
print(np.max(a1, axis=1)) # returns the maximum value in each row
# print(np.max(a1, axis=1, keepdims=True).reshape(3,1)) # same as above but retains its dimension better for visualization

[[48.  6. 76.]
 [31. 91. 49.]
 [93.  5. 54.]]

93.0
[93. 91. 76.]
[76. 91. 93.]


In [14]:
# mean/median/std/var
print(np.mean(a1), end="\n\n") # returns the mean of all the elements in the array
# print(np.median(a1), end="\n\n") # returns the median of all the elements in the array
# print(np.std(a1), end="\n\n") # returns the standard deviation of all the elements in the array
# print(np.var(a1), end="\n\n") # returns the variance of all the elements in the array

50.333333333333336



**Operation along Axis:**
- Aggregation operations can be performed on the entire array or along a specific axis.
- In 2D array axis 0 -> operation on entire col & axis 1 -> operation on entire row

**Deeper Unerstanding:** For multidimensional arrays
- Axis is the dimension along which the operation is performed. For example, in a 2D array, axis 0 refers to the columns and axis 1 refers to the rows. So, if we perform an aggregation operation along axis 0, it will be performed on each column and if we perform it along axis 1, it will be performed on each row.

- In general, for an n-dimensional array, axis 0 refers to the first dimension, axis 1 refers to the second dimension, and so on. So, for a 3D array, axis 0 refers to the depth, axis 1 refers to the rows, and axis 2 refers to the columns.

In [15]:
# Aggregation Operations: 4D Array
a = np.array([[[1,2,3], 
               [4,5,6]],

               [[7,1,9], 
               [10,11,3]]])

print(np.max(a), end="\n--------------------\n")
print(np.max(a, axis=0), end="\n--------------------\n")
print(np.max(a, axis=1), end="\n--------------------\n")
print(np.max(a, axis=2), end="\n--------------------\n")

11
--------------------
[[ 7  2  9]
 [10 11  6]]
--------------------
[[ 4  5  6]
 [10 11  9]]
--------------------
[[ 3  6]
 [ 9 11]]
--------------------


In [16]:
# Aggregation Operations: 4D Array with keepdims=True
print(np.max(a, axis=2, keepdims=True), end="\n--------------------\n")

[[[ 3]
  [ 6]]

 [[ 9]
  [11]]]
--------------------


### **Mathematical Functions**
- NumPy provides a wide range of mathematical functions that can be applied to arrays. 
- These functions operate *element-wise on the array*, meaning they are applied to each element of the array independently. Some of the commonly used mathematical functions include:
    - np.sin(), np.cos(), np.tan() -> Trigonometric functions
    - np.exp() -> Exponential function
    - np.log() -> Natural logarithm
    - np.sqrt() -> Square root
    - np.abs() -> Absolute value
    - etc.

In [17]:
# Trignometric functions
print(np.sin(a1), end="\n\n") # returns the sine of each element in the array
# print(np.cos(a1), end="\n\n") # returns the cosine of each element in the array

[[-0.76825466 -0.2794155   0.56610764]
 [-0.40403765  0.10598751 -0.95375265]
 [-0.94828214 -0.95892427 -0.55878905]]



In [18]:
print(np.exp(a1), end="\n\n") # returns the exponential of each element in the array
# print(np.log(a1), end="\n\n") # returns the natural logarithm of each element in the array
# print(np.sqrt(a1), end="\n\n") # returns the square root of each element in the array
# print(np.abs(a1), end="\n\n") # returns the absolute value of each element in the array

[[7.01673591e+20 4.03428793e+02 1.01480039e+33]
 [2.90488497e+13 3.31740010e+39 1.90734657e+21]
 [2.45124554e+40 1.48413159e+02 2.83075330e+23]]



In [19]:
a = np.array([1, 2, 3])
print(np.exp(a), end="\n\n") # returns the exponential of each element in the array

[ 2.71828183  7.3890561  20.08553692]



### **Approximation Functions**
1. np.round()
2. np.floor()
3. np.ceil()

In [20]:
a = np.array([1.2, 2.5, 3.7])

1. np.round() -> Rounds values to the nearest integer (or specified decimals).
    - NumPy uses round half to even:
        - np.round(2.5)  # 2.0
        - np.round(3.5)  # 4.0

In [21]:
print(np.round(a))        # [1., 2., 4.]
print(np.round(a, 1))     # round to 1 decimal place


[1. 2. 4.]
[1.2 2.5 3.7]


In [22]:
print(np.round(2.5))  # 2.0
print(np.round(3.5))  # 4.0

2.0
4.0


In [23]:
print(np.round(a, 0))
print(np.round(a,3))

[1. 2. 4.]
[1.2 2.5 3.7]


2. np.floor() -> Rounds values down to the nearest smaller integer.
    - Always goes downward
    - Works differently for negatives:
        - np.floor(-1.2)  # -2.0

In [24]:
print(np.floor(a)) # rounds down to the nearest smaller integer

[1. 2. 3.]


3. np.ceil() -> Rounds values up to the nearest larger integer.
    - Always goes upward
    - Works differently for negatives:
        - np.ceil(-1.2)  # -1.0

In [25]:
print(np.ceil(a)) # rounds up to the nearest larger integer

[2. 3. 4.]


### **Dot Product**

In [26]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])