### **Indexing and Slicing**

In [1]:
import numpy as np

In [78]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
a[:2, 1::]

array([[1, 2, 3],
       [5, 6, 7]])

In [92]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [93]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [95]:
a3[0, 1]

array([3, 4, 5])

In [99]:
a3[1, : , 1]

array([10, 13, 16])

In [100]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [102]:
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])