In [1]:
import numpy as np

In [2]:
a = np.arange(100).reshape(10,10)

In [ ]:
print(a[[0, 3, 4, 5, 6, 9]])
# another way to do the same thing is using np.take() function


[[ 0  1  2  3  4  5  6  7  8  9]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [90 91 92 93 94 95 96 97 98 99]]
