# Learning NumPy

In [15]:
import numpy as np

In [16]:
arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimensions of Array

#### **0-D Array**
- Also known as Scalar

In [27]:
# A zero dimensional array is also called a scalar in numpy 

a = np.array(13)

print(a)

13


#### **1D Array**
- An array that has scalars as its elements is called 1-d array.

In [28]:
b = np.array([1,2,3,4,5])
print(b)

[1 2 3 4 5]


#### **2D Array**
- An array that has 1-D arrays as its elements is called a 2-D array.
- These are often used to represent matrix or 2nd order tensors.



In [25]:
c = np.array([[1,2,3], [4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


### **3D Array**
- An array that has 2d array as its elements is called a 3d array
- these are often used to represent matrix or 3rd order tensors

In [24]:
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## **Checking the dimension of an array**

In [29]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
